apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "chart.name" . }}-role"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - list
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "chart.name" . }}-rolebinding"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "chart.name" . }}-role"
subjects:
  - kind: ServiceAccount
    name: "{{include "chart.serviceAccountName" .}}"
    namespace: "{{ .Release.Namespace }}"
